name: HenMac Tahoe Full

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 9999

    steps:
    - name: Download Assets
      run: |
        curl -L -o wallpaper.png https://github.com/arifkembiri/RDP-Windows-2022-Tailscale/blob/main/wallpaper.png?raw=true
        
    - name: Install Tailscale
      run: |
        brew install tailscale
        
    - name: Start and Authenticate Tailscale
      run: |
        sudo tailscaled > /dev/null 2>&1 &
        sleep 5
        sudo tailscale up
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        
    - name: Enable Screen Sharing (Mac RDP/VNC)
      run: |
        # تغییر رمز عبور runner با ایجاد ترمینال مجازی (PTY)
        sudo python3 -c 'import pty, os, time
        pid, fd = pty.fork()
        if pid == 0:
            os.execlp("passwd", "passwd", "runner")
        else:
            time.sleep(0.5)
            os.write(fd, b"MacPass123!\n")
            time.sleep(0.5)
            os.write(fd, b"MacPass123!\n")
            time.sleep(0.5)'
        
        # فعال‌سازی قابلیت ریموت دسکتاپ/Screen Sharing مک
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
        
    - name: Get Tailscale IP and Access Info
      run: |
        tailscale_ip=$(sudo tailscale ip -4)
        echo "=================================="
        echo "Tailscale IP: $tailscale_ip"
        echo "Username: runner"
        echo "Password: MacPass123!"
        echo "Protocol: VNC (Use a VNC Viewer or Apple Screen Sharing)"
        echo "=================================="
        
    - name: Successfully made! Keeping the runner alive.
      run: |
        while true; do sleep 60; done
